Sundaland/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Sundaland.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Sundaland.Controllers
{
    public class PurchaseController : Controller
    {
        public IPurchaseRepository repo { get; set; }
        public Basket basket { get; set; }

        public PurchaseController(IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

Sundaland/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sundaland.Models;
using Sundaland.Infrastructure;

namespace Sundaland.Pages
{
    public class CartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public Basket Basket { get; set; }
        public string ReturnUrl { get; set; }

        public CartModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            Basket = b;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookID, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookID);

            // Add item to basket
            Basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            Basket.RemoveItem(Basket.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Sundaland/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sundaland.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Sundaland/Pages/Cart.cshtml
@page
@model Sundaland.Pages.CartModel
@{
}

<!-- Masthead -->
<header class="masthead-cart">
    <div class="container">
        <div class="masthead-cart-heading">CART</div>
        <div class="masthead-cart-subheading">Below you can find the books in your shopping cart</div>
    </div>
</header>

<div class="row">
    <div class="col m-5">

        <!-- Buttons -->
        <div class="row mb-4">
            <div class="col-12">
                <div class="text-center">
                    <a class="btn btn-secondary" href="@Model.ReturnUrl">Continue Shopping</a>
                    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
                </div>
            </div>
        </div>

        <!-- Cart -->
        <div class="row">
            <div class="col">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Book</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                            <th scope="col">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var i in Model.Basket.Items)
                        {
                            <tr>
                                <td>@i.Book.Title</td>
                                <td>@i.Quantity</td>
                                <td>$@i.Book.Price.ToString("N")</td>
                                <td>$@((i.Quantity * i.Book.Price).ToString("N"))</td>
                                <td class="text-center">
                                    <form method="post" asp-page-handler="Remove">
                                        <input type="hidden" name="bookID" value="@i.Book.BookId" />
                                        <input type="hidden" name="returnURL" value="@Model.ReturnUrl" />
                                        <button type="submit" class="btn btn-danger btn-small">Remove</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3">Total: </td>
                            <td colspan="1">$@Model.Basket.CalculateTotal().ToString("N")</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

Sundaland/Pages/PurchaseCompleted.cshtml
@page
@model Sundaland.Pages.PurchaseCompletedModel
@{
}

<header class="masthead-cart">
    <div class="container">
        <div class="masthead-cart-heading">THANK YOU</div>
        <div class="masthead-cart-subheading">Your purchase has been made.</div>
    </div>
</header>
<div class="row m-5">
    <div class="col">
        <a class="btn btn-primary" asp-controller="Home" asp-action="Booklist">Continue Shopping</a>
    </div>
</div>

Sundaland/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />

    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Sundaland</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Booklist">Book List</a></li>
                    <li class="nav-item"><a class="nav-link" asp-page="/Cart">Cart</a></li>
                    <li class="nav-item"><a class="nav-link" asp-page="/Admin/Index">Admin</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()

    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2021</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                    <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>


    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>